version: "3.7"

services:
  rabbit:
    hostname: rabbit
    image: rabbitmq:latest

    environment:
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    links:
      - rabbit
    depends_on:
      - rabbit
